#ifndef FLOWCONTROL_H
#define FLOWCONTROL_H

/*
VRIJE UNIVERSITEIT AMSTERDAM
FACULTY OF SCIENCE
B. COMPUTER SCIENCE
COURSE: PROJECT APPLICATION DEVELOPMENT (X_400556)
RICARDO BURGOS LARA (2627499)
JUNE 2019
*/

// IJVM BRANCHING INSTRUCTIONS
// ===========================

// GOTO INSTRUCTION (OPCODE 0xA7)
void GOTO(short offset);

// IFEQ INSTRUCTION (OPCODE 0x99)
void IFEQ(short offset);

// IFLT INSTRUCTION (OPCODE 0x9B)
void IFLT(short offset);

// ICMPEQ INSTRUCTION (OPCODE 0x9F)
void ICMPEQ(short offset);

#endif /* FLOWCONTROL_H */
