#ifndef LOCALVARS_H
#define LOCALVARS_H

/*
VRIJE UNIVERSITEIT AMSTERDAM
FACULTY OF SCIENCE
B. COMPUTER SCIENCE
COURSE: PROJECT APPLICATION DEVELOPMENT (X_400556)
RICARDO BURGOS LARA (2627499)
JUNE 2019
*/

// LOCAL VARIABLES
// ===============

// LDC_W INSTRUCTION (OPCODE 0x13)
void LDC_W(uint16_t index);

// ILOAD INSTRUCTION (OPCODE 0x15)
void ILOAD(word_t index);

// ISTORE INSTRUCTION (OPCODE 0x36)
void ISTORE(word_t index);

// IINC INSTRUCTION (OPCODE 0x84)
void IINC(word_t index, word_t cons);

// WIDE + IINC
void WIDE_IINC(short index, word_t cons);

// WIDE INSTRUCTION (OPCODE 0xC4)
void WIDE(word_t inst, short index);

#endif /* LOCALVARS_H */
